-----ACTIVIDADES: TABLAS ANIDADAS-----

--Obtener el número de direcciones que tiene cada ciudad en los identificadores 1 y 2.
SELECT ID, APELLIDOS, CIUDAD, COUNT(*) AS NUMERO FROM EJEMPLO_TABLA_CONTENEDORA, TABLE(DIREC) TD
WHERE ID = 1 OR ID = 2 GROUP BY ID, CIUDAD, APELLIDOS ORDER BY ID;

--Obtener la ciudad con más direcciones para el identificador 1.
SELECT MAX(D.CIUDAD) FROM EJEMPLO_TABLA_CONTENEDORA, TABLE(DIREC) D WHERE ID = 1;

--Realiza una consulta para mostrar el nombre de las calles asociadas a cada apellido.
SELECT APELLIDOS, CALLE FROM EJEMPLO_TABLA_CONTENEDORA, TABLE(DIREC) TD; 

/*Realizar un procedimiento para insertar direcciones en la tabla que contiene la 
tabla anidada*/
  
CREATE OR REPLACE PROCEDURE INSERTAR_DIRECCIONES (PARAMID NUMBER, APE VARCHAR, OBJDIREC DIRECCION)
IS EXISTEID NUMBER;
BEGIN
  --COMPROBAR SI EXISTE ID
  SELECT COUNT(ID) INTO EXISTEID FROM EJEMPLO_TABLA_CONTENEDORA WHERE ID = PARAMID;
  
  IF EXISTEID = 0 THEN
      INSERT INTO EJEMPLO_TABLA_CONTENEDORA VALUES( PARAMID, APE,
      TABLA_ANIDADA ( OBJDIREC ));
      DBMS_OUTPUT.PUT_LINE('FILA INSERTADA');
      COMMIT;
  END IF ;
  
   IF EXISTEID > 0 THEN
      DBMS_OUTPUT.PUT_LINE('ERROR, Ya existe un regstro con el ID: '||PARAMID||', en la tabla');
  END IF;
END;

BEGIN
  INSERTAR_DIRECCIONES(4, 'Chueca', DIRECCION ('Avenida Ciudad de Soria', 'TARAZONA', 50016));
  COMMIT;
END;

SELECT ID, APELLIDOS, DIRECCION.* FROM EJEMPLO_TABLA_CONTENEDORA, 
TABLE(DIREC) DIRECCION;

SELECT ID, APELLIDOS, CURSOR(SELECT TD.CALLE, TD.CIUDAD FROM TABLE(DIREC) TD )
FROM EJEMPLO_TABLA_CONTENEDORA;