-----ACTIVIDADES: MÉTODOS-----

CREATE OR REPLACE TYPE BODY ALUMNO AS MEMBER FUNCTION CALCULAR_MEDIA RETURN MEDIA IS
MEDIA NUMBER;
BEGIN
  MEDIA := EVA1 * 0.15 + EVA2 * 0.35 + EVA3 * 0.5;
  MEDIA := MEDIA/3;
END;
